// Generated from oss-config/kr_sleep/moodist/config/moodist-sounds.catalog.20260706.001.json
// Keep audio files remote/cacheable so the mini program package stays small.

const SLEEP_MOODIST_TOTAL_BYTES = 108129987;

const SLEEP_MOODIST_CATEGORIES = [
    {
        "id": "nature",
        "title": "Nature",
        "titleZh": "自然",
        "mark": "林",
        "soundCount": 12
    },
    {
        "id": "rain",
        "title": "Rain",
        "titleZh": "雨声",
        "mark": "雨",
        "soundCount": 8
    },
    {
        "id": "animals",
        "title": "Animals",
        "titleZh": "动物",
        "mark": "兽",
        "soundCount": 16
    },
    {
        "id": "urban",
        "title": "Urban",
        "titleZh": "城市",
        "mark": "城",
        "soundCount": 7
    },
    {
        "id": "places",
        "title": "Places",
        "titleZh": "场所",
        "mark": "所",
        "soundCount": 16
    },
    {
        "id": "transport",
        "title": "Transport",
        "titleZh": "交通",
        "mark": "行",
        "soundCount": 6
    },
    {
        "id": "things",
        "title": "Things",
        "titleZh": "物件",
        "mark": "物",
        "soundCount": 16
    },
    {
        "id": "noise",
        "title": "Noise",
        "titleZh": "噪音",
        "mark": "噪",
        "soundCount": 3
    }
];

const SLEEP_MOODIST_SOUNDS = [
    {
        "id": "river",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "River",
        "name": "河流",
        "mark": "河",
        "desc": "自然 · River",
        "srcPath": "/sounds/nature/river.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/river.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/river.mp3",
        "bytes": 3895214,
        "sha256": "b0360cd39425a23f7957a152ec61113226f423a9e2e08071d5f37200357e6289",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "waves",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Waves",
        "name": "海浪",
        "mark": "海",
        "desc": "自然 · Waves",
        "srcPath": "/sounds/nature/waves.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/waves.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/waves.mp3",
        "bytes": 2347690,
        "sha256": "40c670e678b5ee19ff67a8c322490b1f7d2d53124cf9e8b07efd329138aaa8f8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "campfire",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Campfire",
        "name": "篝火",
        "mark": "篝",
        "desc": "自然 · Campfire",
        "srcPath": "/sounds/nature/campfire.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/campfire.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/campfire.mp3",
        "bytes": 3245619,
        "sha256": "9625b15c7f6a4a2d16db937f0e1042762421f9a3ab74f60235bd63654bba13db",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "wind",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Wind",
        "name": "风声",
        "mark": "风",
        "desc": "自然 · Wind",
        "srcPath": "/sounds/nature/wind.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/wind.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/wind.mp3",
        "bytes": 1606823,
        "sha256": "556ec1d90038aa92f754de84d58e8973693836b1e0358834536ca7824f40c973",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "howling-wind",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Howling Wind",
        "name": "呼啸风",
        "mark": "呼",
        "desc": "自然 · Howling Wind",
        "srcPath": "/sounds/nature/howling-wind.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/howling-wind.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/howling-wind.mp3",
        "bytes": 522840,
        "sha256": "dd00c875c58c033d2f3b94e247d2b5a366ed529a659cc2d19e00dd84ad0e464d",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "wind-in-trees",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Wind in Trees",
        "name": "林间风",
        "mark": "林",
        "desc": "自然 · Wind in Trees",
        "srcPath": "/sounds/nature/wind-in-trees.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/wind-in-trees.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/wind-in-trees.mp3",
        "bytes": 1294948,
        "sha256": "b29f775dda9789004aaceee392e124eaa35c0386d27f99b93a639185d98f6b4b",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "waterfall",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Waterfall",
        "name": "瀑布",
        "mark": "瀑",
        "desc": "自然 · Waterfall",
        "srcPath": "/sounds/nature/waterfall.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/waterfall.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/waterfall.mp3",
        "bytes": 551904,
        "sha256": "46d0848f5876d0f461e8439f812464742710f5f6d236baa977f382d794c60b0a",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "walk-in-snow",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Walk in Snow",
        "name": "踩雪",
        "mark": "踩",
        "desc": "自然 · Walk in Snow",
        "srcPath": "/sounds/nature/walk-in-snow.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/walk-in-snow.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/walk-in-snow.mp3",
        "bytes": 925248,
        "sha256": "11d89616a1fff14d3c8c57efd88d8d1f66189a2105b13b22b63d886e10e8308c",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "walk-on-leaves",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Walk on Leaves",
        "name": "踩落叶",
        "mark": "踩",
        "desc": "自然 · Walk on Leaves",
        "srcPath": "/sounds/nature/walk-on-leaves.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/walk-on-leaves.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/walk-on-leaves.mp3",
        "bytes": 310632,
        "sha256": "a7f49dc2253c7ce58399865d518f947e377fcf6e78e0d53b270c3497d4021c52",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "walk-on-gravel",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Walk on Gravel",
        "name": "踩碎石",
        "mark": "踩",
        "desc": "自然 · Walk on Gravel",
        "srcPath": "/sounds/nature/walk-on-gravel.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/walk-on-gravel.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/walk-on-gravel.mp3",
        "bytes": 1148568,
        "sha256": "0029d593b2803f035912a4695b499df60d23333e2781f848b243a0b35f5dc16e",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "droplets",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Droplets",
        "name": "水滴",
        "mark": "水",
        "desc": "自然 · Droplets",
        "srcPath": "/sounds/nature/droplets.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/droplets.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/droplets.mp3",
        "bytes": 798168,
        "sha256": "d21f0af60663a03b477739a425ddc59be394ff60ddd1a877bff280b352a57d77",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "jungle",
        "categoryId": "nature",
        "categoryTitle": "Nature",
        "categoryTitleZh": "自然",
        "label": "Jungle",
        "name": "丛林",
        "mark": "丛",
        "desc": "自然 · Jungle",
        "srcPath": "/sounds/nature/jungle.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/nature/jungle.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/nature/jungle.mp3",
        "bytes": 4077048,
        "sha256": "a0ac0b48a8e28d3dde17203e386a722afafe057d1b5d1fb5d13918175a440335",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "light-rain",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Light Rain",
        "name": "小雨",
        "mark": "小",
        "desc": "雨声 · Light Rain",
        "srcPath": "/sounds/rain/light-rain.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/light-rain.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/light-rain.mp3",
        "bytes": 3775087,
        "sha256": "967eab5ddc2b84808a05fea757460d51461e9dc56e72a3d1490bbb58e7bc6578",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "heavy-rain",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Heavy Rain",
        "name": "大雨",
        "mark": "大",
        "desc": "雨声 · Heavy Rain",
        "srcPath": "/sounds/rain/heavy-rain.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/heavy-rain.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/heavy-rain.mp3",
        "bytes": 541741,
        "sha256": "6910161b347a4f616bc42d0b3118982c243d149fe45e55fef74c9a9e1aa08560",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "thunder",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Thunder",
        "name": "雷声",
        "mark": "雷",
        "desc": "雨声 · Thunder",
        "srcPath": "/sounds/rain/thunder.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/thunder.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/thunder.mp3",
        "bytes": 2193449,
        "sha256": "c96dde1068d5c96a40ad47cccc767a88d907b3d3fdcb84819e18b81dcd6bd2bd",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "rain-on-window",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Rain on Window",
        "name": "窗上雨",
        "mark": "窗",
        "desc": "雨声 · Rain on Window",
        "srcPath": "/sounds/rain/rain-on-window.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/rain-on-window.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/rain-on-window.mp3",
        "bytes": 838145,
        "sha256": "781add053a83a0a9ac2a6ee2ccc937fed24872d479830c0c98cd70ed03689fe9",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "rain-on-car-roof",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Rain on Car Roof",
        "name": "车顶雨",
        "mark": "车",
        "desc": "雨声 · Rain on Car Roof",
        "srcPath": "/sounds/rain/rain-on-car-roof.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/rain-on-car-roof.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/rain-on-car-roof.mp3",
        "bytes": 245005,
        "sha256": "5e16d3e97c97a3a130d13a1300d5ccdd3ed8b7788dc9f76262ead0e4eb8a07d7",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "rain-on-umbrella",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Rain on Umbrella",
        "name": "伞上雨",
        "mark": "伞",
        "desc": "雨声 · Rain on Umbrella",
        "srcPath": "/sounds/rain/rain-on-umbrella.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/rain-on-umbrella.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/rain-on-umbrella.mp3",
        "bytes": 1040122,
        "sha256": "f31a565bdf853fbf6baba8495fdfed91f161c55756540819ee13dbbca98ab8c0",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "rain-on-tent",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Rain on Tent",
        "name": "帐篷雨",
        "mark": "帐",
        "desc": "雨声 · Rain on Tent",
        "srcPath": "/sounds/rain/rain-on-tent.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/rain-on-tent.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/rain-on-tent.mp3",
        "bytes": 1494072,
        "sha256": "427d0a06042c5154345ed95de49b2aebf465716766f64891e49f87c3e7cde787",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "rain-on-leaves",
        "categoryId": "rain",
        "categoryTitle": "Rain",
        "categoryTitleZh": "雨声",
        "label": "Rain on Leaves",
        "name": "叶上雨",
        "mark": "叶",
        "desc": "雨声 · Rain on Leaves",
        "srcPath": "/sounds/rain/rain-on-leaves.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/rain/rain-on-leaves.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/rain/rain-on-leaves.mp3",
        "bytes": 697080,
        "sha256": "66669f1e4f90b94016cd3287f7c3b18fd5b76dff7939617b3ba5ec7c92b587ac",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "birds",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Birds",
        "name": "鸟鸣",
        "mark": "鸟",
        "desc": "动物 · Birds",
        "srcPath": "/sounds/animals/birds.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/birds.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/birds.mp3",
        "bytes": 2059536,
        "sha256": "f9b022ed2df9f727a8e84e614b25965112dfe2bbb30cdf8c3db0442ae1eed489",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "seagulls",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Seagulls",
        "name": "海鸥",
        "mark": "海",
        "desc": "动物 · Seagulls",
        "srcPath": "/sounds/animals/seagulls.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/seagulls.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/seagulls.mp3",
        "bytes": 519900,
        "sha256": "ceae3d3a3c57e6c383c86e4a427b538379299133ba595e3b4f40e051886c13a8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "crickets",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Crickets",
        "name": "蟋蟀",
        "mark": "蟋",
        "desc": "动物 · Crickets",
        "srcPath": "/sounds/animals/crickets.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/crickets.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/crickets.mp3",
        "bytes": 2841144,
        "sha256": "126bf1620193fa43a711d3cf6658a06f9fef5bd4eb42bf2ae48da0da1b73605c",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "wolf",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Wolf",
        "name": "狼嚎",
        "mark": "狼",
        "desc": "动物 · Wolf",
        "srcPath": "/sounds/animals/wolf.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/wolf.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/wolf.mp3",
        "bytes": 587749,
        "sha256": "b87652f48a9e24bd47a0bcf18b3e8f61368521148bdb384c908677a460ae56c6",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "owl",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Owl",
        "name": "猫头鹰",
        "mark": "猫",
        "desc": "动物 · Owl",
        "srcPath": "/sounds/animals/owl.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/owl.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/owl.mp3",
        "bytes": 97309,
        "sha256": "7fcd61d5953f564930220bc2579d6071068977f92c7bf5ed6117a57112c55a82",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "frog",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Frog",
        "name": "蛙鸣",
        "mark": "蛙",
        "desc": "动物 · Frog",
        "srcPath": "/sounds/animals/frog.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/frog.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/frog.mp3",
        "bytes": 1572960,
        "sha256": "c41fbbbfbe896a11fd19c0f8dc9185a000462239ff971625ac8eaedd05480b8c",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "dog-barking",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Dog Barking",
        "name": "狗叫",
        "mark": "狗",
        "desc": "动物 · Dog Barking",
        "srcPath": "/sounds/animals/dog-barking.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/dog-barking.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/dog-barking.mp3",
        "bytes": 226488,
        "sha256": "470bd3edaf2e37f3f0c78f0779d773ae59466e4965494875f1c0f4de6bfe0604",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "horse-gallop",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Horse Gallop",
        "name": "马蹄",
        "mark": "马",
        "desc": "动物 · Horse Gallop",
        "srcPath": "/sounds/animals/horse-gallop.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/horse-gallop.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/horse-gallop.mp3",
        "bytes": 169968,
        "sha256": "60d455c6d45732b21fdc3fdfc3c517a37d5f0248e3b7b3274939ab2177e633e6",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "cat-purring",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Cat Purring",
        "name": "猫呼噜",
        "mark": "猫",
        "desc": "动物 · Cat Purring",
        "srcPath": "/sounds/animals/cat-purring.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/cat-purring.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/cat-purring.mp3",
        "bytes": 450384,
        "sha256": "a779a2a3fe77b08722517e2e1a4f8ecbfb59a6282a74e46f0e9244d6cfdf230e",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "crows",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Crows",
        "name": "乌鸦",
        "mark": "乌",
        "desc": "动物 · Crows",
        "srcPath": "/sounds/animals/crows.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/crows.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/crows.mp3",
        "bytes": 775776,
        "sha256": "d39e6732f7713152f697de53053feffe10fc911aa6b7494e01bdca2731edabf1",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "whale",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Whale",
        "name": "鲸声",
        "mark": "鲸",
        "desc": "动物 · Whale",
        "srcPath": "/sounds/animals/whale.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/whale.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/whale.mp3",
        "bytes": 360552,
        "sha256": "e88047b74a6566e07994454d5d6c5ab5ca400485d61d0ee74a5218184187dc17",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "beehive",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Beehive",
        "name": "蜂巢",
        "mark": "蜂",
        "desc": "动物 · Beehive",
        "srcPath": "/sounds/animals/beehive.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/beehive.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/beehive.mp3",
        "bytes": 978816,
        "sha256": "97a42f09b8b4bf2bb2b6eceb7f1f67a7cde599d16252140102fcf4c3af41c6a8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "woodpecker",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Woodpecker",
        "name": "啄木鸟",
        "mark": "啄",
        "desc": "动物 · Woodpecker",
        "srcPath": "/sounds/animals/woodpecker.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/woodpecker.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/woodpecker.mp3",
        "bytes": 167784,
        "sha256": "b2c66c84d6d9ef6d9cc6d064d2da7b9068f994d1e18080f6a62deaa786b18eaf",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "chickens",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Chickens",
        "name": "鸡群",
        "mark": "鸡",
        "desc": "动物 · Chickens",
        "srcPath": "/sounds/animals/chickens.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/chickens.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/chickens.mp3",
        "bytes": 5017248,
        "sha256": "c869f4c5e046d7fefca787363fbec4f466fbf2be5493954eca9ee11a67397d38",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "cows",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Cows",
        "name": "牛群",
        "mark": "牛",
        "desc": "动物 · Cows",
        "srcPath": "/sounds/animals/cows.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/cows.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/cows.mp3",
        "bytes": 557928,
        "sha256": "a1675bfe879d428e9e0079c1ca40ab583774489c1b26894e3e0c25bd0f8516d8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "sheep",
        "categoryId": "animals",
        "categoryTitle": "Animals",
        "categoryTitleZh": "动物",
        "label": "Sheep",
        "name": "羊群",
        "mark": "羊",
        "desc": "动物 · Sheep",
        "srcPath": "/sounds/animals/sheep.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/animals/sheep.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/animals/sheep.mp3",
        "bytes": 716640,
        "sha256": "e1f144b6cbbaf736c83372edbeee7aba65eba215e4789d0670eaa7dc6ad135fa",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "highway",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Highway",
        "name": "高速路",
        "mark": "高",
        "desc": "城市 · Highway",
        "srcPath": "/sounds/urban/highway.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/highway.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/highway.mp3",
        "bytes": 1671552,
        "sha256": "3de274910ddffa6b1ebfce67875aff87b4b7a4c662e49fbb822e5e39458006b5",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "road",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Road",
        "name": "道路",
        "mark": "道",
        "desc": "城市 · Road",
        "srcPath": "/sounds/urban/road.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/road.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/road.mp3",
        "bytes": 1548480,
        "sha256": "df23f3692a02823fe000966d9d0a38c76094958ab26f11e76448c09d41875cd8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "ambulance-siren",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Ambulance Siren",
        "name": "救护车",
        "mark": "救",
        "desc": "城市 · Ambulance Siren",
        "srcPath": "/sounds/urban/ambulance-siren.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/ambulance-siren.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/ambulance-siren.mp3",
        "bytes": 337224,
        "sha256": "5ba2cefd6677e97be596117771a8394ebdb51905530b72578b5913675033e2a4",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "busy-street",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Busy Street",
        "name": "繁忙街道",
        "mark": "繁",
        "desc": "城市 · Busy Street",
        "srcPath": "/sounds/urban/busy-street.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/busy-street.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/busy-street.mp3",
        "bytes": 2328744,
        "sha256": "3f819591a58f280683ab934e9c6a1b90c58531ec5920826e9d887668a0f757e2",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "crowd",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Crowd",
        "name": "人群",
        "mark": "人",
        "desc": "城市 · Crowd",
        "srcPath": "/sounds/urban/crowd.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/crowd.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/crowd.mp3",
        "bytes": 610200,
        "sha256": "720313446ff6dd117f271bcb5082d3d78a038dd284fe9d3e3a4ceb158bcaeafa",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "traffic",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Traffic",
        "name": "车流",
        "mark": "车",
        "desc": "城市 · Traffic",
        "srcPath": "/sounds/urban/traffic.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/traffic.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/traffic.mp3",
        "bytes": 452324,
        "sha256": "3fa2fe742335124d0226f4ba4a9cb86bbc08e1d82d9b3ef6971cff74035cd61f",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "fireworks",
        "categoryId": "urban",
        "categoryTitle": "Urban",
        "categoryTitleZh": "城市",
        "label": "Fireworks",
        "name": "烟花",
        "mark": "烟",
        "desc": "城市 · Fireworks",
        "srcPath": "/sounds/urban/fireworks.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/urban/fireworks.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/urban/fireworks.mp3",
        "bytes": 581400,
        "sha256": "5436e6e89037d5ccf10a27fdb9164566bf68d4628c3537bcac32e8853989e514",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "cafe",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Cafe",
        "name": "咖啡馆",
        "mark": "咖",
        "desc": "场所 · Cafe",
        "srcPath": "/sounds/places/cafe.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/cafe.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/cafe.mp3",
        "bytes": 1776720,
        "sha256": "04b818f9e7c31d57c7f0d522bcf7d9f708c728f046d009953e4fbc18723a0300",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "airport",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Airport",
        "name": "机场",
        "mark": "机",
        "desc": "场所 · Airport",
        "srcPath": "/sounds/places/airport.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/airport.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/airport.mp3",
        "bytes": 4501440,
        "sha256": "9bb9a5d0426c1d865ea9a66d06bc81d63ef40bb418b48bc3819850b95000c9c0",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "church",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Church",
        "name": "教堂",
        "mark": "教",
        "desc": "场所 · Church",
        "srcPath": "/sounds/places/church.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/church.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/church.mp3",
        "bytes": 772224,
        "sha256": "c71217c3b55113b057ee1d82e57b173be184d68b1e3cf53b3fcc17b8792f69ec",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "temple",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Temple",
        "name": "寺庙",
        "mark": "寺",
        "desc": "场所 · Temple",
        "srcPath": "/sounds/places/temple.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/temple.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/temple.mp3",
        "bytes": 1558056,
        "sha256": "680ffbb188ac4068ab775d9da505b0dc6a1fac2e424b9f1ed6d857574f36c44c",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "construction-site",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Construction Site",
        "name": "工地",
        "mark": "工",
        "desc": "场所 · Construction Site",
        "srcPath": "/sounds/places/construction-site.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/construction-site.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/construction-site.mp3",
        "bytes": 1571208,
        "sha256": "51309aadc58e78d0fdba194cfbeb7dfe84fbfba430899e5df4d8b884aadf18eb",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "underwater",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Underwater",
        "name": "水下",
        "mark": "水",
        "desc": "场所 · Underwater",
        "srcPath": "/sounds/places/underwater.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/underwater.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/underwater.mp3",
        "bytes": 526008,
        "sha256": "addd91f799f3b77d8032c32745a0c039804502eb1c65039790dae66428e27164",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "crowded-bar",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Crowded Bar",
        "name": "酒吧",
        "mark": "酒",
        "desc": "场所 · Crowded Bar",
        "srcPath": "/sounds/places/crowded-bar.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/crowded-bar.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/crowded-bar.mp3",
        "bytes": 855192,
        "sha256": "3afbd498ed30d84b5050878ed1656eebb378e69b4d9c62b15615a42ffb8fd5ab",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "night-village",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Night Village",
        "name": "夜晚村庄",
        "mark": "夜",
        "desc": "场所 · Night Village",
        "srcPath": "/sounds/places/night-village.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/night-village.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/night-village.mp3",
        "bytes": 2282322,
        "sha256": "9f012d72f5923208c223065d727a01afecc7d3253064c2e868dc658c33369f8a",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "subway-station",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Subway Station",
        "name": "地铁站",
        "mark": "地",
        "desc": "场所 · Subway Station",
        "srcPath": "/sounds/places/subway-station.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/subway-station.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/subway-station.mp3",
        "bytes": 2243112,
        "sha256": "4b749d4c6d9f9a9b09744325bc358eca80440ba98debdd1ca69a8fcc3cc6dade",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "office",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Office",
        "name": "办公室",
        "mark": "办",
        "desc": "场所 · Office",
        "srcPath": "/sounds/places/office.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/office.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/office.mp3",
        "bytes": 1965408,
        "sha256": "32691ad3d1f0cd6175a4e648ad15c5fd354ad0e59a3ce0b246fd7cf89d9a4169",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "supermarket",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Supermarket",
        "name": "超市",
        "mark": "超",
        "desc": "场所 · Supermarket",
        "srcPath": "/sounds/places/supermarket.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/supermarket.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/supermarket.mp3",
        "bytes": 2315472,
        "sha256": "a33a739ef44a4794d5c0b58b93057312f85d628eac19e45fcb57c70a420f8b66",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "carousel",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Carousel",
        "name": "旋转木马",
        "mark": "旋",
        "desc": "场所 · Carousel",
        "srcPath": "/sounds/places/carousel.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/carousel.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/carousel.mp3",
        "bytes": 2326344,
        "sha256": "cd1d17f381c10b3a9adb966e34786f150241c424cf279d2c98d0bba6df16e750",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "laboratory",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Laboratory",
        "name": "实验室",
        "mark": "实",
        "desc": "场所 · Laboratory",
        "srcPath": "/sounds/places/laboratory.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/laboratory.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/laboratory.mp3",
        "bytes": 384384,
        "sha256": "bc07a653b11b7bd43959124aa5d946613735f2ad130856b43535b305a3ff09af",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "laundry-room",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Laundry Room",
        "name": "洗衣房",
        "mark": "洗",
        "desc": "场所 · Laundry Room",
        "srcPath": "/sounds/places/laundry-room.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/laundry-room.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/laundry-room.mp3",
        "bytes": 737186,
        "sha256": "b24f418d7d1b931312944f2383fcca0f56fe5c397b8e8571cc3ab1b27f701da4",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "restaurant",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Restaurant",
        "name": "餐厅",
        "mark": "餐",
        "desc": "场所 · Restaurant",
        "srcPath": "/sounds/places/restaurant.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/restaurant.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/restaurant.mp3",
        "bytes": 3552736,
        "sha256": "e4e7c25aa81c25bcae0ef010b3fecbdf08371b8af675ecd29972d7a561ddecaa",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "library",
        "categoryId": "places",
        "categoryTitle": "Places",
        "categoryTitleZh": "场所",
        "label": "Library",
        "name": "图书馆",
        "mark": "图",
        "desc": "场所 · Library",
        "srcPath": "/sounds/places/library.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/places/library.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/places/library.mp3",
        "bytes": 3825455,
        "sha256": "95095ef77ed7f1d1c2550b6f39d95cde31f72b37d8023c1dfd7c22931d84fe05",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "train",
        "categoryId": "transport",
        "categoryTitle": "Transport",
        "categoryTitleZh": "交通",
        "label": "Train",
        "name": "火车",
        "mark": "火",
        "desc": "交通 · Train",
        "srcPath": "/sounds/transport/train.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/transport/train.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/transport/train.mp3",
        "bytes": 1277043,
        "sha256": "ee81ed9e0ce6bfc14ce21209615e6f7156384c8213f8c80b5fae3665005ef788",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "inside-a-train",
        "categoryId": "transport",
        "categoryTitle": "Transport",
        "categoryTitleZh": "交通",
        "label": "Inside a Train",
        "name": "车厢内",
        "mark": "车",
        "desc": "交通 · Inside a Train",
        "srcPath": "/sounds/transport/inside-a-train.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/transport/inside-a-train.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/transport/inside-a-train.mp3",
        "bytes": 1441920,
        "sha256": "8689c8f151910752fd94fce9c78ce6d48a4d6653c25f966f056f34e6ef448459",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "airplane",
        "categoryId": "transport",
        "categoryTitle": "Transport",
        "categoryTitleZh": "交通",
        "label": "Airplane",
        "name": "飞机",
        "mark": "飞",
        "desc": "交通 · Airplane",
        "srcPath": "/sounds/transport/airplane.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/transport/airplane.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/transport/airplane.mp3",
        "bytes": 840264,
        "sha256": "170fcd68d60ebe89ac26425a0c38c437b70071cc4919419bbb0cbc92a3cb5af8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "submarine",
        "categoryId": "transport",
        "categoryTitle": "Transport",
        "categoryTitleZh": "交通",
        "label": "Submarine",
        "name": "潜艇",
        "mark": "潜",
        "desc": "交通 · Submarine",
        "srcPath": "/sounds/transport/submarine.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/transport/submarine.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/transport/submarine.mp3",
        "bytes": 696408,
        "sha256": "739e7ae10aa770522b0007482813f8961567fda8cf2941fce46acfe00fdd18e8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "sailboat",
        "categoryId": "transport",
        "categoryTitle": "Transport",
        "categoryTitleZh": "交通",
        "label": "Sailboat",
        "name": "帆船",
        "mark": "帆",
        "desc": "交通 · Sailboat",
        "srcPath": "/sounds/transport/sailboat.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/transport/sailboat.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/transport/sailboat.mp3",
        "bytes": 2186472,
        "sha256": "8701ec1f21561d53c006cf2af4dd540a1b952ed56da4315d382c70a8c01d120f",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "rowing-boat",
        "categoryId": "transport",
        "categoryTitle": "Transport",
        "categoryTitleZh": "交通",
        "label": "Rowing Boat",
        "name": "划船",
        "mark": "划",
        "desc": "交通 · Rowing Boat",
        "srcPath": "/sounds/transport/rowing-boat.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/transport/rowing-boat.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/transport/rowing-boat.mp3",
        "bytes": 597072,
        "sha256": "c4347ae2fa806079198c96c13937e17be7a084c976d566846e322aeefece84d1",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "keyboard",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Keyboard",
        "name": "键盘",
        "mark": "键",
        "desc": "物件 · Keyboard",
        "srcPath": "/sounds/things/keyboard.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/keyboard.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/keyboard.mp3",
        "bytes": 388702,
        "sha256": "2499954ba838ce1b32b79560a2ab273209ae350bb9988490738ed2e2b23f82ae",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "typewriter",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Typewriter",
        "name": "打字机",
        "mark": "打",
        "desc": "物件 · Typewriter",
        "srcPath": "/sounds/things/typewriter.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/typewriter.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/typewriter.mp3",
        "bytes": 341160,
        "sha256": "0d56f3a9482e7edad9a6e58130d733883c89f36f51e1c8dd9fde7a3b5cf276b8",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "paper",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Paper",
        "name": "纸张",
        "mark": "纸",
        "desc": "物件 · Paper",
        "srcPath": "/sounds/things/paper.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/paper.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/paper.mp3",
        "bytes": 156480,
        "sha256": "6aecf96cbcb2403188c010bcdae37de74b604c494dda3097b5cc0a206f686741",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "clock",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Clock",
        "name": "时钟",
        "mark": "时",
        "desc": "物件 · Clock",
        "srcPath": "/sounds/things/clock.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/clock.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/clock.mp3",
        "bytes": 90674,
        "sha256": "45283d30ccc1ccebab2ddb84dbaaaedf5265275c33cb7c4c8defce9451059160",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "wind-chimes",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Wind Chimes",
        "name": "风铃",
        "mark": "风",
        "desc": "物件 · Wind Chimes",
        "srcPath": "/sounds/things/wind-chimes.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/wind-chimes.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/wind-chimes.mp3",
        "bytes": 2255187,
        "sha256": "212558c58fdb5b8f490b9c1d9b6f3c7469d025b4feff4df4014bff60d0422cf9",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "singing-bowl",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Singing Bowl",
        "name": "颂钵",
        "mark": "颂",
        "desc": "物件 · Singing Bowl",
        "srcPath": "/sounds/things/singing-bowl.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/singing-bowl.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/singing-bowl.mp3",
        "bytes": 431808,
        "sha256": "9b86534b01679a113a26da201f6160d604c9408ddd6effb00e38c5be78f0192e",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "ceiling-fan",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Ceiling Fan",
        "name": "吊扇",
        "mark": "吊",
        "desc": "物件 · Ceiling Fan",
        "srcPath": "/sounds/things/ceiling-fan.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/ceiling-fan.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/ceiling-fan.mp3",
        "bytes": 179273,
        "sha256": "c2c009912df561236cc3ca2fb428384ae63f5f869d5178b0a62aabe856df86fb",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "dryer",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Dryer",
        "name": "烘干机",
        "mark": "烘",
        "desc": "物件 · Dryer",
        "srcPath": "/sounds/things/dryer.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/dryer.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/dryer.mp3",
        "bytes": 136692,
        "sha256": "6d666dd1936172ac237915f5dc035d242deddd8ff1a78a765073eda18f8e3e2f",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "slide-projector",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Slide Projector",
        "name": "幻灯机",
        "mark": "幻",
        "desc": "物件 · Slide Projector",
        "srcPath": "/sounds/things/slide-projector.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/slide-projector.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/slide-projector.mp3",
        "bytes": 1888392,
        "sha256": "f87b98c4d5f1d5979679a870928700baa03c78a52785eaa25941373c16f0f5f2",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "boiling-water",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Boiling Water",
        "name": "沸水",
        "mark": "沸",
        "desc": "物件 · Boiling Water",
        "srcPath": "/sounds/things/boiling-water.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/boiling-water.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/boiling-water.mp3",
        "bytes": 526603,
        "sha256": "9c2e35cbd002c0b13aa82301781878654c6fe651325de8be971721ccb95128a1",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "bubbles",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Bubbles",
        "name": "气泡",
        "mark": "气",
        "desc": "物件 · Bubbles",
        "srcPath": "/sounds/things/bubbles.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/bubbles.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/bubbles.mp3",
        "bytes": 102912,
        "sha256": "96f743156f8f9402f1fa7341415d3d9a4bc09316fe94e27c07ce45d211a18c5b",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "tuning-radio",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Tuning Radio",
        "name": "调频收音机",
        "mark": "调",
        "desc": "物件 · Tuning Radio",
        "srcPath": "/sounds/things/tuning-radio.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/tuning-radio.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/tuning-radio.mp3",
        "bytes": 769551,
        "sha256": "2ed7619d3a98c5298728a7e3fc60971cadf0a573b7f1ce46d11a8d69e53becd6",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "morse-code",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Morse Code",
        "name": "摩斯电码",
        "mark": "摩",
        "desc": "物件 · Morse Code",
        "srcPath": "/sounds/things/morse-code.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/morse-code.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/morse-code.mp3",
        "bytes": 228312,
        "sha256": "a00a81bbbcafdcdb2196054941827ecf9d2075ff7459f5794e6b6acabc979b10",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "washing-machine",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Washing Machine",
        "name": "洗衣机",
        "mark": "洗",
        "desc": "物件 · Washing Machine",
        "srcPath": "/sounds/things/washing-machine.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/washing-machine.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/washing-machine.mp3",
        "bytes": 191760,
        "sha256": "f468aaf120141cb618085d33aba190e81f8e85ba6efe5f292ff0a920edabf955",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "vinyl-effect",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Vinyl Effect",
        "name": "黑胶噪声",
        "mark": "黑",
        "desc": "物件 · Vinyl Effect",
        "srcPath": "/sounds/things/vinyl-effect.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/vinyl-effect.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/vinyl-effect.mp3",
        "bytes": 1556698,
        "sha256": "037f7a6ac2a78c1378381048b40049b4960801a4f1e2a209991a64f8744fa46d",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "windshield-wipers",
        "categoryId": "things",
        "categoryTitle": "Things",
        "categoryTitleZh": "物件",
        "label": "Windshield Wipers",
        "name": "雨刷",
        "mark": "雨",
        "desc": "物件 · Windshield Wipers",
        "srcPath": "/sounds/things/windshield-wipers.mp3",
        "originalSrc": "https://moodist.mvze.net/sounds/things/windshield-wipers.mp3",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/things/windshield-wipers.mp3",
        "bytes": 207528,
        "sha256": "858490d7480c62728d976b2aee26193c282f5f0aace7a1bf3001994b7f02d93f",
        "ext": "mp3",
        "type": "audio/mpeg",
        "defaultVolume": 28
    },
    {
        "id": "white-noise",
        "categoryId": "noise",
        "categoryTitle": "Noise",
        "categoryTitleZh": "噪音",
        "label": "White Noise",
        "name": "白噪音",
        "mark": "白",
        "desc": "噪音 · White Noise",
        "srcPath": "/sounds/noise/white-noise.wav",
        "originalSrc": "https://moodist.mvze.net/sounds/noise/white-noise.wav",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/noise/white-noise.wav",
        "bytes": 1676232,
        "sha256": "02ccb2013118b57c76607f7e3e5d9d479e5a9aaa7868e1a07194cde77c0ea6dd",
        "ext": "wav",
        "type": "audio/wav",
        "defaultVolume": 22
    },
    {
        "id": "pink-noise",
        "categoryId": "noise",
        "categoryTitle": "Noise",
        "categoryTitleZh": "噪音",
        "label": "Pink Noise",
        "name": "粉红噪音",
        "mark": "粉",
        "desc": "噪音 · Pink Noise",
        "srcPath": "/sounds/noise/pink-noise.wav",
        "originalSrc": "https://moodist.mvze.net/sounds/noise/pink-noise.wav",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/noise/pink-noise.wav",
        "bytes": 1676972,
        "sha256": "075eecefd60c4103da3ec8672db1c96ba54f073f8a5bc4e7cc1b587c96854fb4",
        "ext": "wav",
        "type": "audio/wav",
        "defaultVolume": 22
    },
    {
        "id": "brown-noise",
        "categoryId": "noise",
        "categoryTitle": "Noise",
        "categoryTitleZh": "噪音",
        "label": "Brown Noise",
        "name": "棕色噪音",
        "mark": "棕",
        "desc": "噪音 · Brown Noise",
        "srcPath": "/sounds/noise/brown-noise.wav",
        "originalSrc": "https://moodist.mvze.net/sounds/noise/brown-noise.wav",
        "remoteSrc": "https://enoss.aorenlan.fun/kr_sleep/moodist/sounds/noise/brown-noise.wav",
        "bytes": 913096,
        "sha256": "b7e4209f2bb4c2ca37e7cf0b21393e2264703d43bea36b4b5c837b8496bbe578",
        "ext": "wav",
        "type": "audio/wav",
        "defaultVolume": 22
    }
];

module.exports = {
    SLEEP_MOODIST_TOTAL_BYTES,
    SLEEP_MOODIST_CATEGORIES,
    SLEEP_MOODIST_SOUNDS
};
